# Text Classification Assignment

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import sklearn.metrics

from re import search

## Reading 'dialog_acts.dat' Dataset

In [2]:
with open('dialog_acts.dat', 'r') as f:
    data = f.readlines()
    data = list(map(lambda x: x.rstrip("\n").split(" ", 1), data))
    
df = pd.DataFrame(np.array(data), columns = ['label', 'text'])

In [3]:
df.head(3)

label                                               text
0  inform  im looking for a moderately priced restaurant ...
1  inform                                   any part of town
2  inform                                        bistro food

## Pre-Processing

Looking for null values, irrelevant or noisy text (literally, removing 'tv_noise' and 'noise') and repeated values. Formatting labels into numbers.

In [18]:
df['label_id'] = df['label'].factorize()[0]
label_dict = df[['label','label_id']].drop_duplicates().set_index('label_id')

label_dict

label
label_id          
0           inform
1          confirm
2           affirm
3          request
4         thankyou
5             null
6              bye
7          reqalts
8           negate
9            hello
10          repeat
11             ack
12         restart
13            deny
14         reqmore

In [8]:
from sklearn.model_selection import train_test_split
# X - independent features (excluding target variable).
# y - dependent variables (target we're looking to predict).

X_train, X_test, y_train, y_test = train_test_split(
    df['text'], df['label_id'], test_size=0.15, random_state=10
)

In [16]:
from sklearn.feature_extraction.text import TfidfVectorizer

tfidf = TfidfVectorizer(sublinear_tf=True, # scale the words frequency in logarithmic scale
                        min_df=5, # remove the words which has occurred in less than ‘min_df’ number of files
                        ngram_range=(1, 2), # don't know what role n-grams play in vectorisation
                        stop_words='english', # it removes stop words which are predefined in ‘english’.
                        lowercase=True # everything to lowercase
                        )

features = tfidf.fit_transform(text_train).toarray()
targets = label_train

print(features)
print(targets)

[[0. 0. 0. ... 0. 0. 0.]
 [0. 1. 0. ... 0. 0. 0.]
 [0. 1. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
11472    0
25465    3
8867     3
25417    4
24660    0
        ..
9372     6
7291     3
17728    3
7293     0
17673    7
Name: label_id, Length: 21675, dtype: int64


## Evaluations

### Baseline Systems

### Proper Models (Random Forest, Multinomial NB, Logistic Regression)

NameError: name 'RandomForestClassifier' is not defined